language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

allow_failures:
  - php: hhvm
  - php: nightly

before_script:
  - composer install --dev

script:
  - vendor/bin/phpspec run -v

